_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  INSTANCE_DROP: 
    ISON: False 
    THRESH_CLS: 4.0
    THRESH_REG: 4.0
    RPN_DROP: 0.3
    OPERATE_ITER: 4000 # 4000 
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 20
  
# INPUT:
#   MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800, 832, 864, 896, 928, 960, 992, 1024, 1056, 1088, 1120, 1152, 1184, 1216)
#   MAX_SIZE_TRAIN: 4000
#   MIN_SIZE_TEST: 1333
#   MAX_SIZE_TEST: 2000
DATASETS:
  TRAIN: ('voc_2012_trainval_wsl',) #pseudo  # voc_2007_trainval_wsl  voc_2007_trainval_wsl voc_2007_trainval_pseudo_top1/2
  TEST: ('voc_2012_test_gt',)
# SOLVER:
#   IMS_PER_BATCH: 16
#   STEPS: (5000, 7000)
#   MAX_ITER: 8500  # 17.4 epochs 5000 7000 8500
#   WARMUP_ITERS: 30 #30
#   CHECKPOINT_PERIOD: 1000
#   BASE_LR: 0.02
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800, 832, 864, 896, 928, 960, 992, 1024, 1056, 1088, 1120, 1152, 1184, 1216)
  MAX_SIZE_TRAIN: 2000
  MIN_SIZE_TEST: 688
  MAX_SIZE_TEST: 4000
SOLVER:
  IMS_PER_BATCH: 16 #@###########
  STEPS: (10000, 14000)
  MAX_ITER: 16000  # 17.4 epochs 5000 7000 8500
  WARMUP_ITERS: 60 #30
  CHECKPOINT_PERIOD: 1000
  BASE_LR: 0.015 #@############
  # CLIP_GRADIENT:
  #   ENABLED: True
  #   CLIP_TYPE: VALUE
  #   CLIP_VALUE: 30.0
TEST:
  AUG:
    ENABLED: True
    MIN_SIZES: (480, 576, 688, 864, 1000, 1200)
    MAX_SIZE: 2000
    FLIP: True
  EVAL_PERIOD: 1000
OUTPUT_DIR: "WeakSAM/SoS-WSOD/voc12_retrain"