MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50" 
  WSOD_ON: True
  FASTER_RCNN: False
  ROI_HEADS:
    SCORE_THRESH: 0.0
    NMS: 0.3
  ROI_WEAK_HEAD:
    PREDICTOR: "MISTPredictor"
    LOSS: "RoIRegLoss"
    OICR_P: 0.15
    REGRESS_ON: True
DATASETS:
  TRAIN: ("coco_2014_train",)
  TEST: ("coco_2014_val",)
PROPOSAL_FILES:
  TRAIN: ('/home/junweizhou/WSOD/OD-WSCL/proposal/SAM/MCG-coco_2014_train-boxes.pkl',)
  TEST:  ('/home/junweizhou/WSOD/OD-WSCL/proposal/SAM/MCG-coco_2014_val-boxes.pkl',)
DATALOADER:
  SIZE_DIVISIBILITY: 32
INPUT:
  MIN_SIZE_TRAIN: (480, 576, 688, 864, 1000, 1200) 
  MAX_SIZE_TRAIN: 2000
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 2000
SOLVER:
  IMS_PER_BATCH: 8 
  BASE_LR: 0.00001 
  WEIGHT_DECAY: 0.0005
  STEPS: (82500, 115000) # 82500 115000
  MAX_ITER: 125000 # 125000
  CHECKPOINT_PERIOD: 20000
TEST:
  BBOX_AUG:
    ENABLED: True
    HEUR: "AVG"
    H_FLIP: True
    SCALES: (480, 576, 688, 864, 1000, 1200) 
    MAX_SIZE: 2000
    SCALE_H_FLIP: True