MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://VGGImageNetPretrained/JCJOHNS/VGG-16" 
  BACKBONE:
    CONV_BODY: "VGG16-OICR"
  WSOD_ON: True
  FASTER_RCNN: False
  ROI_HEADS:
    SCORE_THRESH: 0.0
    NMS: 0.3
  ROI_BOX_HEAD:
    POOLER_METHOD: "ROIPool"
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.125,)
    FEATURE_EXTRACTOR: "VGG16.roi_head"
  ROI_WEAK_HEAD:
    PREDICTOR: "MISTPredictor"
    LOSS: "RoIRegLoss"
    OICR_P: 0.15
    REGRESS_ON: True
DB:
  METHOD: 'concrete'
DATASETS:
  TRAIN: ("coco_2014_train",)
  TEST: ("coco_2014_val",)  # ("coco_2017_train",)
PROPOSAL_FILES:
  TRAIN: ('proposal/SAM/COCO/coco-trainboxes.pkl',)
  TEST:  ('proposal/SAM/COCO/coco-valboxes.pkl',)
DATALOADER:
  SIZE_DIVISIBILITY: 32
INPUT:
  MIN_SIZE_TRAIN: (480, 576, 688, 864, 1000, 1200) 
  MAX_SIZE_TRAIN: 2000
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 2000
SOLVER:
  IMS_PER_BATCH: 8 
  BASE_LR: 0.00001 
  WEIGHT_DECAY: 0.0005
  BIAS_LR_FACTOR: 2
  WEIGHT_DECAY_BIAS: 0
  STEPS: (82500, 115000) 
  MAX_ITER: 125000
  CHECKPOINT_PERIOD: 20000
  # Currently using: Adam optimizer
TEST:
  BBOX_AUG:
    ENABLED: True
    HEUR: "AVG"
    H_FLIP: True
    SCALES: (480, 576, 688, 864, 1000, 1200) # (800, )  # 
    MAX_SIZE: 2000
    SCALE_H_FLIP: True


# The datasets' path changes are in the wetectron/configs/paths_catalog.py