_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
  RPN:
    POSITIVE_FRACTION: 0.25
    LOSS: "CrossEntropy"
SOLVER:
  LR_SCHEDULER_NAME: "WarmupMultiStepLR"
  STEPS: (30000, 40000)
  MAX_ITER: 50000
  IMG_PER_BATCH_LABEL: 16
  IMG_PER_BATCH_UNLABEL: 16
  BASE_LR: 0.02
DATALOADER:
  SUP_PERCENT: 99.99915
  RANDOM_DATA_SEED: 1
  RANDOM_DATA_SEED_PATH: "./dataseed/coco_baseline.txt"
DATASETS:
  CROSS_DATASET: False
  TRAIN: ("coco_2014_train_wsl", 'coco_2014_valminusminival_wsl')
  TEST: ("coco_2014_minival",)
  
SEMISUPNET:
  Trainer: "ubteacher"
  BBOX_THRESHOLD: 0.7
  TEACHER_UPDATE_ITER: 1
  BURN_UP_STEP: 50000
  EMA_KEEP_RATE: 0.9996
  UNSUP_LOSS_WEIGHT: 4.0
  EVAL_TEACHER: False
  BURN_UP_WITH_STRONG_AUG: False 
# INPUT:
#   MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800, 832, 864, 896, 928, 960, 992, 1024, 1056, 1088, 1120, 1152, 1184, 1216)
#   MAX_SIZE_TRAIN: 2000
#   MIN_SIZE_TEST: 688
#   MAX_SIZE_TEST: 4000
TEST:
  EVAL_PERIOD: 1000
  EVALUATOR: "COCOeval"
  AUG:
    ENABLED: False
    MIN_SIZES: (480, 576, 672, 768, 864, 960, 1056, 1152)
    MAX_SIZE: 4000
    FLIP: True
OUTPUT_DIR: "./output/coco_test/"
