_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
    NORM: "FrozenBN"
  FPN:
    NORM: "FrozenBN"
  RPN:
    POSITIVE_FRACTION: 0.25
    LOSS: "CrossEntropy"
  ROI_HEADS:
    NUM_CLASSES: 20
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_CONV: 4
    NUM_FC: 1
    NORM: "FrozenBN"
SOLVER:
  LR_SCHEDULER_NAME: "WarmupMultiStepLR"
  STEPS: (8000, 10500)
  MAX_ITER: 12000
  IMG_PER_BATCH_LABEL: 8
  IMG_PER_BATCH_UNLABEL: 8
  BASE_LR: 0.01
  CHECKPOINT_PERIOD: 2000
DATALOADER:
  SUP_PERCENT: 99.981
  RANDOM_DATA_SEED: 1
  RANDOM_DATA_SEED_PATH: "./dataseed/VOC07_all.txt"
DATASETS:
  CROSS_DATASET: False
  TRAIN: ("voc_2007_train_wsl", "voc_2007_val_wsl")
  TEST: ("voc_2007_test",)
SEMISUPNET:
  Trainer: "ubteacher"
  BBOX_THRESHOLD: 0.7
  TEACHER_UPDATE_ITER: 1
  BURN_UP_STEP: 12000
  EMA_KEEP_RATE: 0.9996
  UNSUP_LOSS_WEIGHT: 4.0
  BURN_UP_WITH_STRONG_AUG: False
  EVAL_TEACHER: False
TEST:
  EVAL_PERIOD: 1000
  EVALUATOR: "VOCeval"
  AUG:
    ENABLED: False
    MIN_SIZES: (480, 576, 672, 768, 864, 960, 1056, 1152)
    MAX_SIZE: 4000
    FLIP: True
INPUT:
  FORMAT: "RGB"
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800, 832, 864, 896, 928, 960, 992, 1024, 1056, 1088, 1120, 1152, 1184, 1216)
  MAX_SIZE_TRAIN: 2000
  MIN_SIZE_TEST: 688
  MAX_SIZE_TEST: 4000
OUTPUT_DIR: "./output/voc_baseline/"
