_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  META_ARCHITECTURE: "TwoStagePseudoLabGeneralizedRCNN"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  PROPOSAL_GENERATOR:
    NAME: "PseudoLabRPN"
  RPN:
    POSITIVE_FRACTION: 0.25
    LOSS: "CrossEntropy"
  ROI_HEADS:
    NAME: "StandardROIHeadsPseudoLab"
    LOSS: "CrossEntropy"
    NUM_CLASSES: 20
SOLVER:
  LR_SCHEDULER_NAME: "WarmupMultiStepLR"
  STEPS: (8000, 10500)
  MAX_ITER: 12000
  IMG_PER_BATCH_LABEL: 8
  IMG_PER_BATCH_UNLABEL: 8
  BASE_LR: 0.02
  CHECKPOINT_PERIOD: 1000
DATALOADER:
  SUP_PERCENT: 99.987793
  RANDOM_DATA_SEED: 1
  RANDOM_DATA_SEED_PATH: "./dataseed/VOC_all.txt"
DATASETS:
  CROSS_DATASET: False
  TRAIN: ("voc_2007_trainval_wsl",)
  TEST: ("voc_2007_test_gt",)
SEMISUPNET: # Unused 
  Trainer: "ubteacher"
  BBOX_THRESHOLD: 0.7
  TEACHER_UPDATE_ITER: 1
  BURN_UP_STEP: 12000
  EMA_KEEP_RATE: 0.9996
  UNSUP_LOSS_WEIGHT: 4.0
  BURN_UP_WITH_STRONG_AUG: False
  EVAL_TEACHER: False
TEST:
  AUG:
    ENABLED: True
    MIN_SIZES: (480, 576, 688, 864, 1000, 1200)
    MAX_SIZE: 2000
    FLIP: True
  EVAL_PERIOD: 1000
  EVALUATOR: "VOCeval"
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800, 832, 864, 896, 928, 960, 992, 1024, 1056, 1088, 1120, 1152, 1184, 1216)
  MAX_SIZE_TRAIN: 2000
  MIN_SIZE_TEST: 688
  MAX_SIZE_TEST: 4000
OUTPUT_DIR: "./output/voc_baseline/"